name: Build Android app

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
      - name: "Add Android targets"
        run: "rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android"
      - name: "Install cargo-binstall || true"
        run: "cargo install cargo-binstall"
      - name: "Install Dioxus CLI"
        run: "cargo binstall dioxus-cli || true"
      - name: "Update apt"
        run: "sudo apt update"
      - name: "Install dependencies"
        run: "sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev"
      - name: "Install Java"
        run: "sudo apt install default-jre && java -version"
      - name: "Download and install Android SDK manager"
        run: |
          mkdir -p android-sdk/cmdline-tools && mv android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip
          unzip commandlinetools-linux-13114758_latest.zip
          mv cmdline-tools latest
          ./latest/bin/sdkmanager --list
